name: CI/CD Pipeline - Node.js with Docker

on: 
  
  push:
    branches:
      - main
      
     
  pull_request: 
     
     branches: 
       - main

  workflow_dispatch:  
    

jobs: 
   
   build-and-test:
      runs-on: ubuntu-latest

      steps: 
         ## checkout your code
         - name: checkout repository
           uses: actions/checkout@v4

         - name: Show files
           run: ls -la
         
         - name: Setup Node.js
           uses: actions/setup-node@v4
           with: 
              node-version: 18

         - name: Install Dependncies
           run : npm install
           working-directory: ./data-volumes-03-adj-node-code

       
   docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup GitHub Token
        run: |
          echo "machine github.com login $GITHUB_USER password $GITHUB_TOKEN" > $HOME/.netrc
          chmod 600 $HOME/.netrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t sandydvd/my-node-feedback-app:latest ./data-volumes-03-adj-node-code

      # Push Docker image
      - name: Push Docker image
        run: docker push sandydvd/my-node-feedback-app:latest
      

